#!/usr/bin/env bash

COMMAND=$(echo ${1:-generate} | awk '{print tolower($0)}')

# Split into an array as we might have more than one domains to add.
IFS=',' read -ra DOMAIN_ARRAY <<< $DOMAIN

# Set the LE cert name based on the first domain provided.
LE_CERT_NAME=${DOMAIN_ARRAY[0]//\./-}

params=()

if [[ ${USE_STAGING_YN:-N} =~ [yY] ]]; then
  params+=(--staging)
fi

case $COMMAND in
  generate)
    params+=(certonly)
    params+=(--authenticator standalone)
    params+=(--email ${EMAIL})
    for domain in "${DOMAIN_ARRAY[@]}"
    do
      params+=(-d $domain)
    done
    params+=(--cert-name ${LE_CERT_NAME})
    params+=(--agree-tos)
    params+=(--no-eff-email)
    ;;
  renew)
    params+=(renew)
    params+=(--cert-name ${LE_CERT_NAME})
    ;;
  *)
    echo Command $COMMAND unknown. Valid values are \"generate\" or \"renew\".
    exit 1
    ;;
esac

if [[ $DRY_RUN =~ [yY] ]]; then
  params+=(--dry-run)
else
  case $DEPLOY_TARGET in
    LB)
      params+=(--post-hook deploy-cert-to-lb)
      ;;
    WAF)
      echo Feature not implemented. Stay tuned!
      exit 1
      params+=(--post-hook deploy-cert-to-waf)
      ;;
  esac
fi

certbot ${params[@]}
